INSERT INTO public.roles (id)
VALUES
  ('ADMINISTRATOR'),
  ('USERS_CANACCESSUSERS'),
  ('USERS_CANADDUSERS'),
  ('USERS_CANEDITUSERS'),
  ('USERS_CANDELETEUSER'),
  ('ROLES_CANACCESSROLES'),
  ('ROLES_CANADDROLES'),
  ('ROLES_CANEDITROLES'),
  ('ROLES_CANDELETEROLES')
ON CONFLICT (id) DO NOTHING;

UPDATE ROLES SET DESCRIPTION=id;

